name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'turtlethread'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: install dependencies
        run: |
          python -m pip install .[docs,dev]
      - name: run tests and linter
        run: |
          python -m pytest tests
          python -m black --check src tests
      - name: build package
        run: |
          python setup.py sdist bdist-wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
