name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write

jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'turtlethread'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python with TKinter and a virtual X11 frame buffer
        run: |
          sudo apt-get update
          sudo apt-get install tk-dev python3-tk python3 python3-pip
          sudo apt-get install xvfb
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install --user .[dev,docs]
      - name: run linter
        run: |
          python -m black --check src tests
      - name: run tests
        run: |
          # Start virtual display driver
          export DISPLAY=:12
          Xvfb $DISPLAY -screen 0 1920x1080x24 2>/tmp/Xvfb.log & sleep 1
          # Create postscript
          python3 -mpytest tests --cov=turtlethread
      - name: build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
